version: '3.1'
services:
  ghost:
    image: ghost:5.19.3-alpine
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: production
      url: https://archangle.net
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password:
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content

  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:1.21.6
    restart: always
    depends_on:
      - ghost
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
